---
default:
    - debug: false
      open: public/index.html
      extra: -use-network=false -static-link-runtime-shared-libraries
    
library-path:
    - source/swc

source-path:
    - source/classes
    - source/libs
    - ../../source/classes
    - ../../source/libs
    
applications:
    - class: source/classes/example/views/Loader.as
      output: public/loader.swf
      report: public/loader.xml
    
    - class: source/classes/example/views/Main.as
      output: public/main.swf
      report: public/main.xml
      exclude:
            - source/classes/example/views/Loader.as
      
    - class: source/classes/example/views/About.as
      output: public/about.swf
      report: public/about.xml
      exclude:
          - public/loader.xml  
          - public/main.xml


# asdoc:
#     - title: "My ActionScript project"
#       footer: "My ActionScript project footer"
#       output: docs/
#       exclude-dirs: 
#         - source/classes/caurina/